// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cashier/login": {
            "post": {
                "description": "login Cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "login cashier",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_Token"
                        }
                    }
                }
            }
        },
        "/cashier/{cashierId}/logout": {
            "post": {
                "description": "logout Cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "logout cashier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cashier Id",
                        "name": "cashierId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Passcode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            }
        },
        "/cashier/{cashierId}/passcode": {
            "post": {
                "description": "passcode Cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "passcode cashier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cashier Id",
                        "name": "cashierId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Passcode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_Passcode"
                        }
                    }
                }
            }
        },
        "/cashiers": {
            "get": {
                "description": "get cashier list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cashiers"
                ],
                "summary": "get cashier list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-array_Model_Cashier"
                        }
                    }
                }
            },
            "post": {
                "description": "create cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cashiers"
                ],
                "summary": "create cashier",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.Cashier"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            }
        },
        "/cashiers/{cashierId}": {
            "get": {
                "description": "get cashier detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cashiers"
                ],
                "summary": "get cashier detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cashier id",
                        "name": "cashierId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_CashierDetails"
                        }
                    }
                }
            },
            "put": {
                "description": "update cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cashiers"
                ],
                "summary": "get update cashier",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.Cashier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cashiers"
                ],
                "summary": "delete cashier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cashier id",
                        "name": "cashierId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "get category list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "get category list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "skip",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_CategoryList"
                        }
                    }
                }
            },
            "post": {
                "description": "create category",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "create category",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.Category"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Category"
                        }
                    }
                }
            }
        },
        "/categories/{categoryId}": {
            "get": {
                "description": "get category details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "get category details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category id",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Category"
                        }
                    }
                }
            },
            "put": {
                "description": "update category",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "get update category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category id",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.Category"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Category"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete category",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "get delete category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category id",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "order list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "order list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_OrderListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "create order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_OrderResponse"
                        }
                    }
                }
            }
        },
        "/orders/subtotal": {
            "post": {
                "description": "subtotal orders",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "subtotal orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_OrderResponse"
                        }
                    }
                }
            }
        },
        "/orders/{orderId}": {
            "get": {
                "description": "order detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "order detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_OrderDetailResponse"
                        }
                    }
                }
            }
        },
        "/orders/{orderId}/check-download": {
            "get": {
                "description": "checkout order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "checkout order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_CheckOrder"
                        }
                    }
                }
            }
        },
        "/orders/{orderId}/download": {
            "get": {
                "description": "order list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "order list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_OrderListResponse"
                        }
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "description": "list payment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "list payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "skip",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_ListPayment"
                        }
                    }
                }
            },
            "post": {
                "description": "create payment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "create payment",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePayment"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Payment"
                        }
                    }
                }
            }
        },
        "/payments/{paymentId}": {
            "get": {
                "description": "payment details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "payment details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "payment id",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Payment"
                        }
                    }
                }
            },
            "put": {
                "description": "payment details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "payment details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "payment id",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.Payment"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Payment"
                        }
                    }
                }
            },
            "delete": {
                "description": "payment details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "payment details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "payment id",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "product list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "product list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "skip",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "categoryId",
                        "name": "categoryId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "q",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_ProductList"
                        }
                    }
                }
            },
            "post": {
                "description": "create product",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "create product",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProdDiscount"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Product"
                        }
                    }
                }
            }
        },
        "/products/{productId}": {
            "get": {
                "description": "get product details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "get product details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "productId",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_ProductResult"
                        }
                    }
                }
            },
            "put": {
                "description": "update products",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "update products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "productId",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.Product"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-Model_Product"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete product",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "delete product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product id",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-string"
                        }
                    }
                }
            }
        },
        "/revenues": {
            "get": {
                "description": "get revenues",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "get revenues",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_Revenue"
                        }
                    }
                }
            }
        },
        "/solds": {
            "get": {
                "description": "get solds",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "get solds",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response.WebResponse-dto_Sold"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Model.Cashier": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "passcode": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.Category": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.Discount": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "integer"
                },
                "expired_at_format": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "qty": {
                    "type": "integer"
                },
                "result": {
                    "type": "integer"
                },
                "string_format": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.Order": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "integer"
                },
                "cashier_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "is_download": {
                    "type": "integer"
                },
                "payment_types_id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "quantities": {
                    "type": "string"
                },
                "receipt_id": {
                    "type": "string"
                },
                "total_paid": {
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                },
                "total_return": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.Payment": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "payment_type_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.PaymentType": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.Product": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "discountId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "total_final_price": {
                    "type": "integer"
                },
                "total_normal_price": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Model.ProductResponseOrder": {
            "type": "object",
            "properties": {
                "discount": {
                    "$ref": "#/definitions/Model.Discount"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "productId": {
                    "type": "integer"
                },
                "qty": {
                    "type": "integer"
                },
                "total_final_price": {
                    "type": "integer"
                },
                "total_normal_price": {
                    "type": "integer"
                }
            }
        },
        "Model.ProductResult": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/Model.Category"
                },
                "discount": {
                    "$ref": "#/definitions/Model.Discount"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "productId": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                }
            }
        },
        "Model.RevenueResponse": {
            "type": "object",
            "properties": {
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "payment_type_id": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "integer"
                }
            }
        },
        "Model.SoldResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "integer"
                },
                "total_qty": {
                    "type": "integer"
                }
            }
        },
        "Response.WebResponse-Model_Category": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/Model.Category"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-Model_Payment": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/Model.Payment"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-Model_Product": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/Model.Product"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-Model_ProductResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/Model.ProductResult"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-array_Model_Cashier": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Model.Cashier"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_CashierDetails": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CashierDetails"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_CategoryList": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CategoryList"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_CheckOrder": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CheckOrder"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_ListPayment": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ListPayment"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_OrderDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.OrderDetailResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_OrderListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.OrderListResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_OrderResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.OrderResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_Passcode": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Passcode"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_ProductList": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ProductList"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_Revenue": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Revenue"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_Sold": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Sold"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-dto_Token": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Token"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Response.WebResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.CashierDetails": {
            "type": "object",
            "properties": {
                "cashier_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.Category": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CategoryList": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Category"
                    }
                },
                "page": {
                    "$ref": "#/definitions/dto.Pagination"
                }
            }
        },
        "dto.CheckOrder": {
            "type": "object",
            "properties": {
                "is_downloaded": {
                    "type": "boolean"
                }
            }
        },
        "dto.CreatePayment": {
            "type": "object",
            "properties": {
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.Discount": {
            "type": "object",
            "properties": {
                "expiredAt": {
                    "type": "integer"
                },
                "qty": {
                    "type": "integer"
                },
                "result": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ListPayment": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/dto.Pagination"
                },
                "payment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Payment"
                    }
                }
            }
        },
        "dto.LoginDto": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.OrderDetail": {
            "type": "object",
            "properties": {
                "cashier": {
                    "$ref": "#/definitions/Model.Cashier"
                },
                "cashier_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "payment_type": {
                    "$ref": "#/definitions/Model.PaymentType"
                },
                "payment_types_id": {
                    "type": "integer"
                },
                "receipt_id": {
                    "type": "string"
                },
                "total_paid": {
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                },
                "total_return": {
                    "type": "integer"
                }
            }
        },
        "dto.OrderDetailResponse": {
            "type": "object",
            "properties": {
                "orders": {
                    "$ref": "#/definitions/dto.OrderDetail"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Model.Product"
                    }
                }
            }
        },
        "dto.OrderList": {
            "type": "object",
            "properties": {
                "cashier": {
                    "$ref": "#/definitions/Model.Cashier"
                },
                "cashiersId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "orderId": {
                    "type": "integer"
                },
                "paymentTypesId": {
                    "type": "integer"
                },
                "payment_type": {
                    "$ref": "#/definitions/Model.PaymentType"
                },
                "receiptId": {
                    "type": "string"
                },
                "totalPaid": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "integer"
                },
                "totalReturn": {
                    "type": "integer"
                }
            }
        },
        "dto.OrderListResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/dto.Pagination"
                },
                "order": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderList"
                    }
                }
            }
        },
        "dto.OrderResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/Model.Order"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Model.ProductResponseOrder"
                    }
                }
            }
        },
        "dto.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "skip": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.Passcode": {
            "type": "object",
            "properties": {
                "passcode": {
                    "type": "string"
                }
            }
        },
        "dto.Payment": {
            "type": "object",
            "properties": {
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paymentId": {
                    "type": "integer"
                },
                "payment_type_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ProdDiscount": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "integer"
                },
                "discount": {
                    "$ref": "#/definitions/dto.Discount"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                }
            }
        },
        "dto.ProductList": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/dto.Pagination"
                },
                "product_res": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Model.ProductResult"
                    }
                }
            }
        },
        "dto.Revenue": {
            "type": "object",
            "properties": {
                "paymentTypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Model.RevenueResponse"
                    }
                },
                "total_revenue": {
                    "type": "integer"
                }
            }
        },
        "dto.Sold": {
            "type": "object",
            "properties": {
                "total_sold": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Model.SoldResponse"
                    }
                }
            }
        },
        "dto.Token": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Sales api docs",
	Description:      "This is the complete api documentation for sales api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
